update

diff --git a/.github/workflows/.build-for-macos.yml b/.github/workflows/.build-for-macos.yml
--- a/.github/workflows/.build-for-macos.yml
+++ b/.github/workflows/.build-for-macos.yml
@@ -46,8 +46,17 @@ jobs:
       - name: Bundle into dmg
         run: |
           git submodule update --checkout qt/bundle/PyOxidizer
-          diutil detach /Volumes/Anki || true
-          ./ninja bundle
+          max_tries=10
+          i=0
+          until ./ninja bundle
+          do
+              if [ $i -eq $max_tries ]
+              then
+                  echo 'Error: ./ninja bundle did not succeed even after 10 tries.'
+                  exit 1
+              fi
+              i=$((i+1))
+          done
 
       - name: List files in out directory
         run: |
